services:
  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel
      - appliance_repair_laravel

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.appliance_repair.rule=Host(`service.ufamasters.ru`)"
      - "traefik.http.routers.appliance_repair.entrypoints=websecure"
      - "traefik.http.routers.appliance_repair.tls.certresolver=myresolver"
      - "traefik.http.routers.appliance_repair-insecure.rule=Host(`service.ufamasters.ru`)"
      - "traefik.http.routers.appliance_repair-insecure.entrypoints=web"
      - "traefik.http.routers.appliance_repair-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  php:
    build:
      context: .
      dockerfile: docker/php/php.dockerfile
    user: "${UID}:${GID}"

    volumes:
      - ./:/var/www/html
      - ./docker/php/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini

    networks:
      - laravel
    # - appliance_repair_laravel

  mysql:
    image: mysql:8.0.38-debian
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/binlog.cnf:/etc/mysql/conf.d/binlog.cnf:ro
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: docker/composer/composer.dockerfile
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

volumes:
  db_data:

networks:
  appliance_repair_laravel:
    external: true

  laravel:
    driver: bridge
